### DISCUSSION TITLE
Wrong timezone in AWS EC2

### DISCUSSION THREAD

**Discussion by pearldrum** [cpvalente/ontime#1207] [Q&A]
I have installed ontime in docker in EC2 but I can't get it to show anything other than UTC. I have changed the local time zone with no difference.
Anyone else using EC2 and can point me in the right direction?

**Comment by cpvalente** [comment]
> I have installed ontime in docker in EC2 but I can't get it to show anything other than UTC. I have changed the local time zone with no difference. Anyone else using EC2 and can point me in the right direction?

Hi, changing the timezone is done in the docker-compose, from our experience, most issues came from typos on the timezone location. Can you please show what config are you using?

**Reply by pearldrum** [reply]
I have copied the example:
```
version: "3"

services:
  ontime:
    container_name: ontime
    image: getontime/ontime:latest
    ports:
      - "4001:4001/tcp"
      - "8888:8888/udp"
      - "9999:9999/udp"
    volumes:
      - "./ontime-data:/data/"
    environment:
      - TZ=Asia/Singapore
    restart: unless-stopped
```
Which should not result in UTC. When I do it in my home server environment it works which makes me think there is something fishy with EC2. That's why I'm asking if anyone has experience with EC2 and can give me some pointers.
