### DISCUSSION TITLE
Docker - Raspberry Pi - Time Zone

### DISCUSSION THREAD

**Discussion by texasles** [cpvalente/ontime#802] [Q&A]
I've set the timezone in my docker-compose.yml file but can't seem to get it to change in Ontime. My raspberry pi yields the correct date and time when I use "date" in the command line. 

My docker-compose.yml file is as follows:

```
version: "3"

services:
  ontime:
    container_name: ontime
    image: getontime/ontime:latest
    ports:
      - "4001:4001/tcp"
      - "8888:8888/udp"
      - "9999:9999/udp"
    volumes:
      - "./ontime-db:/external/db/"
      - "./ontime-styles:/external/styles/"
    environment:
      -  TZ=America/Chicago
    restart: unless-stopped
```
```

Any suggestions would be great. Thanks.
