### ISSUE TITLE
Ontime DOCKER not saving DB

### ISSUE THREAD

**Issue by sledzik1984** [cpvalente/ontime#1076]
I have problem with ontime in Docker. It doesn't save any settings. For testing purposes I've changed permissions  of folders to 777 but no files are written.

My compose file: 

```
version: "3"

services:
  ontime:
    container_name: ontime
    image: getontime/ontime:latest
    ports:
      - "4001:4001/tcp"
      - "8888:8888/udp"
      - "8888:8888/tcp"
    volumes:
      - "/opt/ontime/ontime-db:/server/preloaded-db"
      - "/opt/ontime/ontime-external:/server/external"
    environment:
      - TZ=Europe/Warsaw
    restart: unless-stopped

```

**Comment by sledzik1984** [comment]
Ok... my compose file was bad but example available on git is also bad.
File should state: 

    volumes:
      - "/opt/ontime/ontime-db:/external/"

**Comment by Punkerschaf** [comment]
Had the same issue.
Solution of @sledzik1984 works for me also.

It seems that only defining volume for `/external/` is necessary, while the folder for _styles_, _projects_ and _external_ are created within. If defined otherwise, they are created but not used.

Is only a documentation thing.

**Comment by cpvalente** [comment]
Hi @sledzik1984 and @Punkerschaf , thank you for this.

I realise that our documentation is out of sync with the docker-hub example where we have fixed this
https://hub.docker.com/r/getontime/ontime

Making a push to documentation now to clarify this

**Comment by cpvalente** [comment]
Hi @sledzik1984 and @Punkerschaf , could you please point me to the documentation that has lead given you incorrect information?

**Comment by sledzik1984** [comment]
I suppose that is some old documentation. It could be very old as I installed Ontime in docker more than one year ago and didn't changed compose till now.

**Comment by cpvalente** [comment]
Ah, I see. 

The internal setup has changed dramatically since v3.
The new docs are at https://docs.getontime.no/

We will anyway improve the documentation here. I will close this issue in favour of a task in the documentation repo

**Comment by Wiibleyde** [comment]
Hello, sorry to reopen this closed ticket, is the /data/ still valid?

Because it doesn't seem to work on my side (nothing in my volume and all my data lost after a restart).

Here is the extract from my `docker-compose.yml` :
```yml
  ontime:
    image: getontime/ontime:latest
    container_name: ontime
    ports:
      - "127.0.0.1:4001:4001/tcp"
      - "127.0.0.1:8888:8888/udp"
    volumes:
      - /home/wiibleyde/Docker-data/ontime/:/data/
    environment:
      - TZ=Europe/Paris
```

Thanks in advance!
