### ISSUE TITLE
Setting TImezone Variable for Docker Container

### ISSUE THREAD

**Issue by ievgeniilarin** [cpvalente/ontime#148]
The timezone is always set to UTC.

It should be possible to set an environmental variable for a timezone.

**Comment by cpvalente** [comment]
Hey @ievgeniilarin, thank you for your message.
The timezone is used as an utility in all the logic and should not affect your setup. The application compares the system clock to the times that you input so there should be no interference 

Am I missing something?

**Comment by ievgeniilarin** [comment]
Yes, the issue is related to the roll mode.

When I run a Docker container the app doesn't respect the host timezone.

**Comment by cpvalente** [comment]
Makes sense. Are you running the docker container locally or hosted in the cloud? 
I was wondering if - as a short term solution - it would be possible to change the timezone of the container

**Comment by ievgeniilarin** [comment]
I'm running the container locally for testing, not a real project.

**Comment by cpvalente** [comment]
Thank you for this. I have added this as a bug and will be looking for a fix.

**Comment by cpvalente** [comment]
Hey, just had a quick look and adding a TZ environment variable in docker compose seemed to do the trick. No changes needed in software. 
Can you please confirm that this is a solution for you?

docker-compose ended up like this
```
version: "3"

services:
  ontime:
    container_name: ontime
    image: getontime/ontime:v1.2.0.1
    ports:
      - "4001:4001/tcp"
      - "127.0.0.1:8888:8888/udp"
    volumes:
      - "./ontime-db:/server/preloaded-db"
    environment:
      - TZ=Asia/Singapore
    restart: unless-stopped

```
